spring:
  application:
    name: service-oauth
  config:
    import:
    optional:
      configserver:
server:
  port: 9100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
